In [33]:
import pandas as pd

In [34]:
data = [["ayush",90],["piyush",80],["rohan",91],["soham",99]]

In [35]:
data

[['ayush', 90], ['piyush', 80], ['rohan', 91], ['soham', 99]]

In [36]:
pd.DataFrame(data, columns=["name","marks"])

     name  marks
0   ayush     90
1  piyush     80
2   rohan     91
3   soham     99

In [37]:
data = {"a": [1,2,3],"b": [4,5,6]}

In [38]:
data

{'a': [1, 2, 3], 'b': [4, 5, 6]}

In [39]:
df = pd.DataFrame(data)

In [40]:
df

   a  b
0  1  4
1  2  5
2  3  6

In [41]:
import numpy as np

In [42]:
arr = np.array([[1,2],[2,3]])

In [43]:
arr

array([[1, 2],
       [2, 3]])

In [44]:
df = pd.DataFrame(arr,columns=["a","b"])

In [45]:
df

   a  b
0  1  2
1  2  3

In [46]:
pd.read_excel(r"C:\Users\rani mahajan\OneDrive\Desktop\pandas\data.xlsx")

    name school  marks
0  ayush    wpu     99
1   chut    wps     98
2  rohan    wpd     97
3  soham    wpf     99
4   yash    wpg     23
5  karan    wph     10

In [47]:
pd.read_csv(r"C:\Users\rani mahajan\OneDrive\Desktop\pandas\data.csv")

    name school  marks
0  ayush    wpu     99
1   chut    wps     98
2  rohan    wpd     97
3  soham    wpf     99
4   yash    wpg     23
5  karan    wph     10

In [50]:
pd.read_json(r"C:\Users\rani mahajan\OneDrive\Desktop\pandas\data.json")

    name    lang
0  ayush  python
1  ayush  python

In [51]:
df =  pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

In [52]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [25]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [26]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [28]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [30]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')