In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\rani mahajan\OneDrive\Desktop\pandas\movies.csv")

In [3]:
df

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
0,Zack and Miri Make a Porno,Romance,The Weinstein Company,70,1.747542,64.0,$41.94,2008.0
1,Youth in Revolt,Comedy,The Weinstein Company,52,1.090000,68.0,$19.62,2010.0
2,You Will Meet a Tall Dark Stranger,Comedy,Independent,35,1.211818,43.0,$26.66,2010.0
3,When in Rome,Comedy,Disney,44,0.000000,15.0,$43.04,2010.0
4,What Happens in Vegas,Comedy,Fox,72,6.267647,28.0,$219.37,2008.0
...,...,...,...,...,...,...,...,...
65,Gnomeo and Juliet,Animation,Disney,52,5.387972,56.0,$193.97,2011.0
66,Ghosts of Girlfriends Past,Comedy,Warner Bros.,47,2.044400,27.0,$102.22,2009.0
67,Four Christmases,Comedy,Warner Bros.,52,2.022925,26.0,$161.83,2008.0
68,Fireproof,Drama,Independent,51,66.934000,40.0,$33.47,2008.0
69,Enchanted,Comedy,Disney,80,NaN,NaN,NaN,NaN

In [4]:
df.sort_values("Year")

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
7,Waitress,Romance,Independent,67,11.089742,89.0,$22.18,2007.0
10,Tyler Perry's Why Did I get Married,Romance,Independent,47,3.724192,46.0,$55.86,2007.0
31,P.S. I Love You,Romance,Independent,82,5.103117,21.0,$153.09,2007.0
18,The Heartbreak Kid,Comedy,Paramount,41,2.129444,30.0,$127.77,2007.0
51,License to Wed,Comedy,Warner Bros.,55,1.980206,8.0,$69.31,2007.0
...,...,...,...,...,...,...,...,...
38,New Year's Eve,Romance,Warner Bros.,48,2.536429,8.0,$142.04,2011.0
43,Midnight in Paris,Romence,Sony,84,8.744706,93.0,$148.66,2011.0
65,Gnomeo and Juliet,Animation,Disney,52,5.387972,56.0,$193.97,2011.0
64,Gnomeo and Juliet,Animation,Disney,52,5.387972,56.0,$193.97,2011.0
69,Enchanted,Comedy,Disney,80,NaN,NaN,NaN,NaN

In [5]:
df.sort_values("Year",ascending=False)

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
34,One Day,Romance,Independent,54,3.682733,37.0,$55.24,2011.0
23,Something Borrowed,Romance,Independent,48,1.719514,15.0,$60.18,2011.0
11,Twilight: Breaking Dawn,Romance,Independent,68,6.383364,26.0,$702.17,2011.0
8,Waiting For Forever,Romance,Independent,53,0.005000,6.0,$0.03,2011.0
5,Water For Elephants,Drama,20th Century Fox,72,3.081421,60.0,$117.09,2011.0
...,...,...,...,...,...,...,...,...
51,License to Wed,Comedy,Warner Bros.,55,1.980206,8.0,$69.31,2007.0
40,Music and Lyrics,Romance,Warner Bros.,70,3.647411,63.0,$145.90,2007.0
54,Knocked Up,Comedy,Universal,83,6.636402,91.0,$219,2007.0
62,Good Luck Chuck,Comedy,Lionsgate,61,2.367685,3.0,$59.19,2007.0
69,Enchanted,Comedy,Disney,80,NaN,NaN,NaN,NaN

In [10]:
df2 = df.sort_values(["Year","Profitability"]).copy()

In [11]:
df2

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
51,License to Wed,Comedy,Warner Bros.,55,1.980206,8.0,$69.31,2007.0
18,The Heartbreak Kid,Comedy,Paramount,41,2.129444,30.0,$127.77,2007.0
62,Good Luck Chuck,Comedy,Lionsgate,61,2.367685,3.0,$59.19,2007.0
36,No Reservations,Comedy,Warner Bros.,64,3.307180,39.0,$92.60,2007.0
40,Music and Lyrics,Romance,Warner Bros.,70,3.647411,63.0,$145.90,2007.0
...,...,...,...,...,...,...,...,...
64,Gnomeo and Juliet,Animation,Disney,52,5.387972,56.0,$193.97,2011.0
65,Gnomeo and Juliet,Animation,Disney,52,5.387972,56.0,$193.97,2011.0
11,Twilight: Breaking Dawn,Romance,Independent,68,6.383364,26.0,$702.17,2011.0
43,Midnight in Paris,Romence,Sony,84,8.744706,93.0,$148.66,2011.0
69,Enchanted,Comedy,Disney,80,NaN,NaN,NaN,NaN

In [19]:
df2.reset_index(drop=True,inplace=True)#drop=True means it drop the index which is writen in the extra row,inplace=true means make the change in df2

In [20]:
df2

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
0,License to Wed,Comedy,Warner Bros.,55,1.980206,8.0,$69.31,2007.0
1,The Heartbreak Kid,Comedy,Paramount,41,2.129444,30.0,$127.77,2007.0
2,Good Luck Chuck,Comedy,Lionsgate,61,2.367685,3.0,$59.19,2007.0
3,No Reservations,Comedy,Warner Bros.,64,3.307180,39.0,$92.60,2007.0
4,Music and Lyrics,Romance,Warner Bros.,70,3.647411,63.0,$145.90,2007.0
...,...,...,...,...,...,...,...,...
65,Gnomeo and Juliet,Animation,Disney,52,5.387972,56.0,$193.97,2011.0
66,Gnomeo and Juliet,Animation,Disney,52,5.387972,56.0,$193.97,2011.0
67,Twilight: Breaking Dawn,Romance,Independent,68,6.383364,26.0,$702.17,2011.0
68,Midnight in Paris,Romence,Sony,84,8.744706,93.0,$148.66,2011.0
69,Enchanted,Comedy,Disney,80,NaN,NaN,NaN,NaN

In [21]:
df2["Rank"] = df2["Audience score %"].rank()

In [22]:
df2

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year,Rank
0,License to Wed,Comedy,Warner Bros.,55,1.980206,8.0,$69.31,2007.0,26.5
1,The Heartbreak Kid,Comedy,Paramount,41,2.129444,30.0,$127.77,2007.0,3.0
2,Good Luck Chuck,Comedy,Lionsgate,61,2.367685,3.0,$59.19,2007.0,34.0
3,No Reservations,Comedy,Warner Bros.,64,3.307180,39.0,$92.60,2007.0,39.0
4,Music and Lyrics,Romance,Warner Bros.,70,3.647411,63.0,$145.90,2007.0,48.5
...,...,...,...,...,...,...,...,...,...
65,Gnomeo and Juliet,Animation,Disney,52,5.387972,56.0,$193.97,2011.0,20.5
66,Gnomeo and Juliet,Animation,Disney,52,5.387972,56.0,$193.97,2011.0,20.5
67,Twilight: Breaking Dawn,Romance,Independent,68,6.383364,26.0,$702.17,2011.0,45.0
68,Midnight in Paris,Romence,Sony,84,8.744706,93.0,$148.66,2011.0,67.5
69,Enchanted,Comedy,Disney,80,NaN,NaN,NaN,NaN,61.0

In [24]:
df2.sort_values("Rank")

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year,Rank
41,You Will Meet a Tall Dark Stranger,Comedy,Independent,35,1.211818,43.0,$26.66,2010.0,1.0
29,Love Happens,Drama,Universal,40,2.004444,18.0,$36.08,2009.0,2.0
1,The Heartbreak Kid,Comedy,Paramount,41,2.129444,30.0,$127.77,2007.0,3.0
38,When in Rome,Comedy,Disney,44,0.000000,15.0,$43.04,2010.0,4.0
42,Killers,Action,Lionsgate,45,1.245333,11.0,$93.40,2010.0,5.0
...,...,...,...,...,...,...,...,...,...
7,Knocked Up,Comedy,Universal,83,6.636402,91.0,$219,2007.0,66.0
59,My Week with Marilyn,Drama,The Weinstein Company,84,0.825800,83.0,$8.26,2011.0,67.5
68,Midnight in Paris,Romence,Sony,84,8.744706,93.0,$148.66,2011.0,67.5
45,Tangled,Animation,Disney,88,1.365692,89.0,$355.01,2010.0,69.0
17,WALL-E,Animation,Disney,89,2.896019,96.0,$521.28,2008.0,70.0

In [26]:
df.rename(columns={"Audience score %":"Audience marks"})

,Film,Genre,Lead Studio,Audience marks,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
0,Zack and Miri Make a Porno,Romance,The Weinstein Company,70,1.747542,64.0,$41.94,2008.0
1,Youth in Revolt,Comedy,The Weinstein Company,52,1.090000,68.0,$19.62,2010.0
2,You Will Meet a Tall Dark Stranger,Comedy,Independent,35,1.211818,43.0,$26.66,2010.0
3,When in Rome,Comedy,Disney,44,0.000000,15.0,$43.04,2010.0
4,What Happens in Vegas,Comedy,Fox,72,6.267647,28.0,$219.37,2008.0
...,...,...,...,...,...,...,...,...
65,Gnomeo and Juliet,Animation,Disney,52,5.387972,56.0,$193.97,2011.0
66,Ghosts of Girlfriends Past,Comedy,Warner Bros.,47,2.044400,27.0,$102.22,2009.0
67,Four Christmases,Comedy,Warner Bros.,52,2.022925,26.0,$161.83,2008.0
68,Fireproof,Drama,Independent,51,66.934000,40.0,$33.47,2008.0
69,Enchanted,Comedy,Disney,80,NaN,NaN,NaN,NaN