In [10]:
import pandas as pd
df =  pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

In [5]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [6]:
df["tip"]

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [7]:
df[['tip','day']]

      tip   day
0    1.01   Sun
1    1.66   Sun
2    3.50   Sun
3    3.31   Sun
4    3.61   Sun
..    ...   ...
239  5.92   Sat
240  2.00   Sat
241  2.00   Sat
242  1.75   Sat
243  3.00  Thur

[244 rows x 2 columns]

In [6]:
df[["tip","day"]]

      tip   day
0    1.01   Sun
1    1.66   Sun
2    3.50   Sun
3    3.31   Sun
4    3.61   Sun
..    ...   ...
239  5.92   Sat
240  2.00   Sat
241  2.00   Sat
242  1.75   Sat
243  3.00  Thur

[244 rows x 2 columns]

In [7]:
df.loc[1]

total_bill     10.34
tip             1.66
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 1, dtype: object

In [8]:
df.loc[4,"tip"]

np.float64(3.61)

In [9]:

df.iloc[4,1]#same output as before

np.float64(3.61)

In [10]:
df.loc[0:2,["tip","day"]]#sliceing
#in loc the last index in included

    tip  day
0  1.01  Sun
1  1.66  Sun
2  3.50  Sun

In [12]:
df.iloc[0:2,0:2]
#  here the the last index is not included

   total_bill   tip
0       16.99  1.01
1       10.34  1.66

In [13]:
df.at[0,"tip"]#this at use to acess only one element

np.float64(1.01)

In [14]:
df.iat[0,0]

np.float64(16.99)

In [28]:
df[df['tip']>6]# only one condtion at one time

     total_bill    tip     sex smoker   day    time  size
23        39.42   7.58    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
183       23.17   6.50    Male    Yes   Sun  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3

In [31]:
df[(df["tip"]>3) & (df["size"]>3)]# two condtion at one time

     total_bill   tip     sex smoker   day    time  size
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
7         26.88  3.12    Male     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
23        39.42  7.58    Male     No   Sat  Dinner     4
44        30.40  5.60    Male     No   Sun  Dinner     4
47        32.40  6.00    Male     No   Sun  Dinner     4
52        34.81  5.20  Female     No   Sun  Dinner     4
54        25.56  4.34    Male     No   Sun  Dinner     4
59        48.27  6.73    Male     No   Sat  Dinner     4
63        18.29  3.76    Male    Yes   Sat  Dinner     4
77        27.20  4.00    Male     No  Thur   Lunch     4
85        34.83  5.17  Female     No  Thur   Lunch     4
95        40.17  4.73    Male    Yes   Fri  Dinner     4
116       29.93  5.07    Male     No   Sun  Dinner     4
125       29.80  4.20  Female     No  Thur   Lunch     6
141       34.30  6.70    Male     No  Thur   Lunch     6
142       41.19  5.00    Male     No  Thur   Lunch     5
143       27.05  5.00  Female     No  Thur   Lunch     6
155       29.85  5.14  Female     No   Sun  Dinner     5
156       48.17  5.00    Male     No   Sun  Dinner     6
157       25.00  3.75  Female     No   Sun  Dinner     4
160       21.50  3.50    Male     No   Sun  Dinner     4
167       31.71  4.50    Male     No   Sun  Dinner     4
180       34.65  3.68    Male    Yes   Sun  Dinner     4
183       23.17  6.50    Male    Yes   Sun  Dinner     4
185       20.69  5.00    Male     No   Sun  Dinner     5
197       43.11  5.00  Female    Yes  Thur   Lunch     4
204       20.53  4.00    Male    Yes  Thur   Lunch     4
211       25.89  5.16    Male    Yes   Sat  Dinner     4
212       48.33  9.00    Male     No   Sat  Dinner     4
219       30.14  3.09  Female    Yes   Sat  Dinner     4

In [11]:
df.query(" size>=4")

     total_bill   tip     sex smoker   day    time  size
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
7         26.88  3.12    Male     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
13        18.43  3.00    Male     No   Sun  Dinner     4
23        39.42  7.58    Male     No   Sat  Dinner     4
25        17.81  2.34    Male     No   Sat  Dinner     4
31        18.35  2.50    Male     No   Sat  Dinner     4
33        20.69  2.45  Female     No   Sat  Dinner     4
44        30.40  5.60    Male     No   Sun  Dinner     4
47        32.40  6.00    Male     No   Sun  Dinner     4
52        34.81  5.20  Female     No   Sun  Dinner     4
54        25.56  4.34    Male     No   Sun  Dinner     4
56        38.01  3.00    Male    Yes   Sat  Dinner     4
59        48.27  6.73    Male     No   Sat  Dinner     4
63        18.29  3.76    Male    Yes   Sat  Dinner     4
77        27.20  4.00    Male     No  Thur   Lunch     4
85        34.83  5.17  Female     No  Thur   Lunch     4
95        40.17  4.73    Male    Yes   Fri  Dinner     4
116       29.93  5.07    Male     No   Sun  Dinner     4
119       24.08  2.92  Female     No  Thur   Lunch     4
125       29.80  4.20  Female     No  Thur   Lunch     6
141       34.30  6.70    Male     No  Thur   Lunch     6
142       41.19  5.00    Male     No  Thur   Lunch     5
143       27.05  5.00  Female     No  Thur   Lunch     6
153       24.55  2.00    Male     No   Sun  Dinner     4
154       19.77  2.00    Male     No   Sun  Dinner     4
155       29.85  5.14  Female     No   Sun  Dinner     5
156       48.17  5.00    Male     No   Sun  Dinner     6
157       25.00  3.75  Female     No   Sun  Dinner     4
159       16.49  2.00    Male     No   Sun  Dinner     4
160       21.50  3.50    Male     No   Sun  Dinner     4
167       31.71  4.50    Male     No   Sun  Dinner     4
180       34.65  3.68    Male    Yes   Sun  Dinner     4
183       23.17  6.50    Male    Yes   Sun  Dinner     4
185       20.69  5.00    Male     No   Sun  Dinner     5
187       30.46  2.00    Male    Yes   Sun  Dinner     5
197       43.11  5.00  Female    Yes  Thur   Lunch     4
204       20.53  4.00    Male    Yes  Thur   Lunch     4
207       38.73  3.00    Male    Yes   Sat  Dinner     4
211       25.89  5.16    Male    Yes   Sat  Dinner     4
212       48.33  9.00    Male     No   Sat  Dinner     4
216       28.15  3.00    Male    Yes   Sat  Dinner     5
219       30.14  3.09  Female    Yes   Sat  Dinner     4
227       20.45  3.00    Male     No   Sat  Dinner     4
230       24.01  2.00    Male    Yes   Sat  Dinner     4

In [38]:
df.query("tip > 3 and size > 3")

     total_bill   tip     sex smoker   day    time  size
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
7         26.88  3.12    Male     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
23        39.42  7.58    Male     No   Sat  Dinner     4
44        30.40  5.60    Male     No   Sun  Dinner     4
47        32.40  6.00    Male     No   Sun  Dinner     4
52        34.81  5.20  Female     No   Sun  Dinner     4
54        25.56  4.34    Male     No   Sun  Dinner     4
59        48.27  6.73    Male     No   Sat  Dinner     4
63        18.29  3.76    Male    Yes   Sat  Dinner     4
77        27.20  4.00    Male     No  Thur   Lunch     4
85        34.83  5.17  Female     No  Thur   Lunch     4
95        40.17  4.73    Male    Yes   Fri  Dinner     4
116       29.93  5.07    Male     No   Sun  Dinner     4
125       29.80  4.20  Female     No  Thur   Lunch     6
141       34.30  6.70    Male     No  Thur   Lunch     6
142       41.19  5.00    Male     No  Thur   Lunch     5
143       27.05  5.00  Female     No  Thur   Lunch     6
155       29.85  5.14  Female     No   Sun  Dinner     5
156       48.17  5.00    Male     No   Sun  Dinner     6
157       25.00  3.75  Female     No   Sun  Dinner     4
160       21.50  3.50    Male     No   Sun  Dinner     4
167       31.71  4.50    Male     No   Sun  Dinner     4
180       34.65  3.68    Male    Yes   Sun  Dinner     4
183       23.17  6.50    Male    Yes   Sun  Dinner     4
185       20.69  5.00    Male     No   Sun  Dinner     5
197       43.11  5.00  Female    Yes  Thur   Lunch     4
204       20.53  4.00    Male    Yes  Thur   Lunch     4
211       25.89  5.16    Male    Yes   Sat  Dinner     4
212       48.33  9.00    Male     No   Sat  Dinner     4
219       30.14  3.09  Female    Yes   Sat  Dinner     4

In [14]:
df.query("tip>4 and size > 4")

     total_bill   tip     sex smoker   day    time  size
125       29.80  4.20  Female     No  Thur   Lunch     6
141       34.30  6.70    Male     No  Thur   Lunch     6
142       41.19  5.00    Male     No  Thur   Lunch     5
143       27.05  5.00  Female     No  Thur   Lunch     6
155       29.85  5.14  Female     No   Sun  Dinner     5
156       48.17  5.00    Male     No   Sun  Dinner     6
185       20.69  5.00    Male     No   Sun  Dinner     5