In [2]:
import pandas as pd

In [22]:
df = pd.read_csv(r"C:\Users\rani mahajan\OneDrive\Desktop\pandas\data_cleaning_sample (1).csv")

In [23]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [6]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [7]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [8]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com    1/5/2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12/11/2019
6  Alice  25.0     New York      F  alice@example.com    1/5/2021
7  Alice  25.0     New York      F  alice@example.com    1/5/2021

In [10]:
df.dropna(axis=1)

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [12]:
df.fillna(0)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [14]:
df["Age"].fillna(df["Age"].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [15]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [16]:
df.fillna(method="ffill")

C:\Users\rani mahajan\AppData\Local\Temp\ipykernel_21708\3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5    David  28.0        Delhi      F     eve@domain.com  12/11/2019
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [17]:
df.fillna(method="bfill")

C:\Users\rani mahajan\AppData\Local\Temp\ipykernel_21708\3896554658.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5    Alice  28.0        Delhi      F     eve@domain.com    1/5/2021
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [18]:
df.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5    David  28.0        Delhi      F     eve@domain.com  12/11/2019
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [19]:
df.bfill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5    Alice  28.0        Delhi      F     eve@domain.com    1/5/2021
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [20]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [21]:
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [25]:
df.duplicated(subset=["Name","Age"])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [26]:
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [30]:
df["City"].str.contains("delhi", case=False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [31]:
df2  = df.dropna().copy()

In [32]:
df2["Age"] = df2["Age"].astype(int)

In [33]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   Age        5 non-null      int64
 2   City       5 non-null      object
 3   Gender     5 non-null      object
 4   Email      5 non-null      object
 5   Join Date  5 non-null      object
dtypes: int64(1), object(5)
memory usage: 280.0+ bytes

In [34]:
df2

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com    1/5/2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12/11/2019
6  Alice   25     New York      F  alice@example.com    1/5/2021
7  Alice   25     New York      F  alice@example.com    1/5/2021

In [35]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [42]:
df2["Age Group"] = df2["Age"].apply(lambda x: "Adult" if x>=30 else "Minor")

In [43]:
df2

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25     New York      F  alice@example.com    1/5/2021     Minor
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Adult
4  David   22       Mumbai      M  david@example.com  12/11/2019     Minor
6  Alice   25     New York      F  alice@example.com    1/5/2021     Minor
7  Alice   25     New York      F  alice@example.com    1/5/2021     Minor

In [44]:
gender_map = {"M":"Male","F":"Female","o":"other"}
df["Gender"] = df["Gender"].map(gender_map)

In [45]:
df

      Name   Age         City  Gender              Email   Join Date
0    Alice  25.0     New York  Female  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021
4    David  22.0       Mumbai    Male  david@example.com  12/11/2019
5      NaN  28.0        Delhi  Female     eve@domain.com         NaN
6    Alice  25.0     New York  Female  alice@example.com    1/5/2021
7    Alice  25.0     New York  Female  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021

In [48]:
df["City"].replace({"Delhi":"New Delhi"})

0       New York
1      New Delhi
2    Los Angeles
3      New Delhi
4         Mumbai
5      New Delhi
6       New York
7       New York
8      New Delhi
Name: City, dtype: object