In [1]:
import pandas as pd 
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

In [2]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [3]:
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [4]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [6]:
pd.merge(employees,departments,on="DeptID")#it give the common deptID and show all the column in both table

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [7]:
pd.merge(employees,departments,on="DeptID", how="left")#Keeps all employees, fills NaN where no match.

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [8]:
pd.merge(employees,departments,on="DeptID", how="right")#right join

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [9]:
pd.merge(employees,departments,on="DeptID", how="outer")#Includes all data, fills missing with NaN

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [16]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"],"score":[123,234]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"],"age":[12,23]})

In [17]:
df1

    Name  score
0  Alice    123
1    Bob    234

In [18]:
df2

      Name  age
0  Charlie   12
1    David   23

In [19]:
pd.concat([df1,df2])

      Name  score   age
0    Alice  123.0   NaN
1      Bob  234.0   NaN
0  Charlie    NaN  12.0
1    David    NaN  23.0

In [20]:
pd.concat([df1,df2],axis=1)#Make sure indexes align when using axis=1

    Name  score     Name  age
0  Alice    123  Charlie   12
1    Bob    234    David   23